name: Build All OSs
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv & deps
        run: |
          pip install uv
          uv pip install --system pyinstaller playwright eel tqdm

      - name: Build
        run: |
          pyinstaller --onefile scraper.py &
          pyinstaller --onefile search.py &
          pyinstaller --onefile setup.py &
          pyinstaller --onefile convert-to-csv.py &
          pyinstaller --onefile --add-data "web:web" main.py &
          wait    background jobs finished
          python -c "import shutil; shutil.copy('settings.example.json','dist/')"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executables-${{ matrix.os }}
          path: dist/*
